version: '3.8'

services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        volumes:
            - ./volumes/etc/:/etc/rabbitmq/
            - ./volumes/data/:/var/lib/rabbitmq/
            - ./volumes/logs/:/var/log/rabbitmq/
        ports:
            - 5672:5672
            - 15672:15672